### ISSUE TITLE
No module named gi

### ISSUE THREAD

**Issue by michaa7** [hkdb/Densify#4]
Thanks for provideing this program. Unfortunatly I does not start here.

Running Debian/sid(uction) fully updated.

After unpacking and moving the files to /opt/Densify, I issued the chmod command as described. Then I issued ./install.sh which worked as it should.

Then I tried to run densify (starting from CL as I use WM fluxbox), but get an error:

> $ /opt/Densify/densify
> Traceback (most recent call last):
>   File "/opt/Densify/densify", line 25, in <module>
>     import gi
> ImportError: No module named gi

python3-gi is newest Debian Version (3.34.0-1)

No clue what to do. Please let me know if you need furthe info.

Thanks

**Comment by hkdb** [comment]
@michaa7  Sorry for the super late reply! I suspect that it's because 0.2.0 runs on Python2 and you don't have gi installed for that. The latest release which is completely on Python3 and just released minutes ago should fix this problem for you without needing any additional configuration. Let me know if that helps.

Thanks!

**Comment by hkdb** [comment]
Closing due to lack of response.
