### ISSUE TITLE
densify does not open

### ISSUE THREAD

**Issue by aarontrom** [hkdb/Densify#6]
Hey, I would love to use densify and I installed it on my customized Manjaro via the software center. The installation was successful, however everytime I want to open it, the mouse button turns into loading for a few seconds and nothing happens. 

When I use the terminal to open densify I get this: 

> [aaron@aaron-pc ~]$ densify
> Traceback (most recent call last):
>   File "densify", line 462, in <module>
>     win = MyWindow()
>   File "densify", line 43, in __init__
>     p = subprocess.Popen(disp, stdout=subprocess.PIPE)
>   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'xrandr'

So I am not sure what to do. I can not even run the AppImage that I downloaded from here: https://github.com/hkdb/Densify/releases/download/v0.3.1/Densify-v0.3.1-x86_64.AppImage

And I was also searching about this 'xrandr' thing in the software center. What I found out was that libxrandr 1.5.2-3 is installed. I have no clue about programming, so maybe these things have nothing to do with each other. 

Do you have an idea what I could try?

**Comment by hkdb** [comment]
Hi @aarontrom ,

Did a quick search and found this: https://github.com/yancharkin/games_nebula/issues/15

Based on that, maybe try installing xorg-xrandr?

I don't have a machine with Manjaro but I do have an Arch box that runs Densify and it looks like xorg-xandr is installed on my system:

```
pacman -Ss xorg-xrandr
extra/xorg-xrandr 1.5.1-2 (xorg-apps xorg) [installed]
    Primitive command line interface to RandR extension
```

In case you ask even though I assume that you know how to since you got this far, the command to install xorg-xrandr is:
```
sudo pacman -S xorg-xrandr
```

That's just my best guess not knowing if you are running xorg, wayland, or other details about your system.

Let me know if that helps...

**Comment by aarontrom** [comment]
Hi @hkdb 

that was it! I just installed xorg-xrandr and now it works :)

Thank you so much for getting back that fast and providing help!

**Comment by hkdb** [comment]
Awesome! Glad it helped! Cheers!
